spring:
  datasource:
    hikari:
#      driver-class-name: org.postgresql.Driver
#      driver-class-name: com.mysql.cj.jdbc.Driver
      username: postgres
      password: powerful090
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: FlowableHikariCP
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-init-sql: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      allow-pool-suspension: false
#      jdbc-url: jdbc:mysql://psawesome.xyz:53306/flowable?useSSL=false&useUnicode=true&characterEncoding=utf8
    url: jdbc:postgresql://psawesome.xyz:31907/flowable
#    url: jdbc:mysql://psawesome.xyz:53306/flowable?useSSL=false&useUnicode=true&characterEncoding=utf8
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        connection:
#          url: jdbc:postgresql://psawesome.xyz:31907/flowable
#          username: postgres
#          password: powerful090
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          driver_class: org.postgresql.Driver
          show_sql: true
          format_sql: true
  liquibase:
#    url: jdbc:postgresql://psawesome.xyz:31907/flowable
#    url: jdbc:mysql://psawesome.xyz:53306/flowable?useSSL=false&useUnicode=true&characterEncoding=utf8
#    user: root
#    password: powerful090
    change-log: /org/flowable/app/db/liquibase/flowable-app-db-changelog.xml
#    change-log: classpath:/org/flowable/app/db/liquibase/
    contexts: development, production
    drop-first: true
    enabled: true
#    labels: development
    liquibase-schema: public
#    liquibase-tablespace: public
#    rollback-file: rollback.xml
#    test-rollback-on-update: false
#    clear-check-sums: false
    database-change-log-lock-table: act_app_databasechangeloglock
    database-change-log-table: act_app_databasechangelog